behaviors:
  Shootair:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 8384
      learning_rate: 3e-4
      beta: 3e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: resnet
      use_recurrent: true
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 512
    summary_freq: 10000