behaviors:
  Shootair:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 40960
      learning_rate: 1e-4
      beta: 6e-3
      epsilon: 0.15
      lambd: 0.94
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      encoding_size: 128
      use_recurrent: true
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.94
        strength: 1.0
        network_settings:   
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
    keep_checkpoints: 5
    checkpoint_interval: 2000000
    max_steps: 310e6
    time_horizon: 256
    summary_freq: 10000
    threaded: true