behaviors:
  Shootair:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 3e-4
      beta: 0.1
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      encoding_size: 128
      use_recurrent: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
    keep_checkpoints: 5
    max_steps: 10e6
    time_horizon: 1000
    summary_freq: 10000
    threaded: true