behaviors:
  Shootair:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 3e-4
      beta: 3e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      encoding_size: 128
      use_recurrent: true
      memory:
        sequence_length: 128
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:   
          normalize: false
          hidden_units: 512
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
    keep_checkpoints: 5
    checkpoint_interval: 8000000
    max_steps: 40e6
    time_horizon: 128
    summary_freq: 100000
    threaded: true