behaviors:
  Shootair:
    trainer_type: sac
    hyperparameters:    
      learning_rate: 3e-4
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 51200
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 4.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:   
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals: 
      extrinsic:    
        gamma: 0.99
        strength: 1.0
        network_settings:   
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
    keep_checkpoints: 5
    checkpoint_interval: 600000
    max_steps: 3000000
    time_horizon: 256
    summary_freq: 10000
    threaded: true